channels:
- pytorch
- nvidia
- conda-forge
- defaults
dependencies:
- numpy=1.26.4
- pandas=2.2.3
- scikit-learn=1.5.2
- scipy=1.13.0
- matplotlib=3.7.2
- regex=2023.8.8
- tabulate=0.9.0
- pillow=10.4.0
- tqdm=4.65.2
- termcolor=2.5.0
- pytorch-cuda=11.6
- torchmetrics=1.4.0.post0
- ipykernel=6.29.5
- python=3.9.20
- pip=24.2
- pip:
  - albumentations==1.4.16
  - ftfy==6.2.0
  - humanhash3==0.0.6
  - opencv-python-headless>=4.9.0.80 
  - torch==1.13.1
  - torchvision==0.14.1
name: crane_env
